<a href="https://colab.research.google.com/github/Nishanta04/SQL/blob/main/DE_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas tabulate

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.13/dist-packages (0.9.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("rentio.db")
cursor = conn.cursor()

In [ ]:
cursor.executescript("""
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS film_category;

CREATE TABLE category (
    category_id INTEGER PRIMARY KEY,
    name TEXT,
    last_update TEXT
);

CREATE TABLE film (
    film_id INTEGER PRIMARY KEY,
    title TEXT,
    length INTEGER,
    release_year INTEGER,
    rating TEXT
);

CREATE TABLE store (
    store_id INTEGER PRIMARY KEY,
    manager_staff_id INTEGER,
    address_id INTEGER,
    last_update TEXT
);

CREATE TABLE staff (
    staff_id INTEGER PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    active INTEGER,
    address_id INTEGER
);

CREATE TABLE film_category (
    film_id INTEGER,
    category_id INTEGER
);
""")

conn.commit() # It saves the DB from RAM to HardDisk

In [ ]:
cursor.executemany(
    "INSERT INTO category VALUES (?, ?, ?)",
    [
        (1, "Action", "2006-02-15 05:03:42"),
        (2, "Animation", "2006-02-15 05:03:42"),
        (3, "Horror", "2006-02-15 05:03:42"),
        (4, "Music", "2006-02-15 05:03:42"),
    ]
)

cursor.executemany(
    "INSERT INTO film VALUES (?, ?, ?, ?, ?)",
    [
        (1, "Iron Man", 126, 2008, "PG-13"),
        (2, "The Incredible Hulk", 112, 2008, "PG-13"),
        (3, "Iron Man 2", 124, 2010, "PG-13"),
        (4, "Thor", 115, 2011, "PG-13"),
    ]
)

cursor.executemany(
    "INSERT INTO film_category VALUES (?, ?)",
    [
        (1, 1),
        (2, 2),
        (3, 1),
        (4, 1),
    ]
)

cursor.executemany(
    "INSERT INTO store VALUES (?, ?, ?, ?)",
    [
        (1, 1, 1, "2006-02-15 05:03:42"),
        (2, 2, 2, "2006-02-15 05:03:43"),
    ]
)

cursor.executemany(
    "INSERT INTO staff VALUES (?, ?, ?, ?, ?, ?)",
    [
        (1, "Mike", "Hillyer", "james.monroe@examplepetstore.com", 1, 1),
        (2, "Jon", "Stephens", "john.c.calhoun@examplepetstore.com", 1, 2),
    ]
)

conn.commit()

In [ ]:
def run_sql(query):
    return pd.read_sql_query(query, conn)

In [ ]:
run_sql("""
SELECT category.name, COUNT(film.film_id) AS film_count
FROM film
JOIN film_category ON film.film_id = film_category.film_id
JOIN category ON category.category_id = film_category.category_id
GROUP BY category.name
ORDER BY film_count ASC
""")

        name  film_count
0  Animation           1
1     Action           3

In [ ]:
run_sql("""
SELECT * FROM film
""")

   film_id                title  length  release_year rating
0        1             Iron Man     126          2008  PG-13
1        2  The Incredible Hulk     112          2008  PG-13
2        3           Iron Man 2     124          2010  PG-13
3        4                 Thor     115          2011  PG-13